@startuml
class App extends javafx.application.Application {
    {static} # FRAME_WIDTH : int
    {static} # FRAME_HEIGHT : int

    {static} +main(args : String...)
}

class DrawableEdge extends javafx.scene.shape.Line
class DrawableNode {
    # currentIncoming : int
    # translateX : SimpleDoubleProperty
    # translateY : SimpleDoubleProperty

    +incrementIncoming() : int
}
class BaseController<StackPane> extends DefaultController {
    # sequence : String
}
abstract class DefaultController<T extends Parent> implements javafx.fxml.Initializable {
    # root : T
    #loadFXML(fxmlFile : String)
    #loadFile(fileChooser : FileChooser, source : TextField)
    #getRoot() : Parent
}
class GraphController<ScrollPane> extends DefaultController {
    # mainController : MainController
    # loadGraphService : LoadGraphService

    #loadGraph()
    #showGraph(graph : Graph)
    #showColumn(graph : Graph, nodes : List<Node>)
    #showNodes(nodes : List<Node>, column : int)
}
class LoadGraphController<GridPane> extends DefaultController {
    # mainController : MainController
    # nodeFile : File
    # edgeFile : File
}
class LoadNewickController<GridPane> extends DefaultController {
    # mainController : MainController
    # nwkFile : File
}
class MainController<BorderPane> extends DefaultController {
    # viewList : Stack<Node>

    +setBaseView(node : Node)
    +setView(node : Node)
    +previousView()
    +exitProgram()
}
class MenuController extends javafx.scene.control.MenuBar {
    # mainController : MainController

    +initFileMenu()
    +initHelpMenu()
    -initWorkspaceMenu()
}
class NewickController<ScrollPane> extends DefaultController {
    # mainController : MainController
    # loadNewickService : LoadNewickService

    +loadTree()
    #showTree(tree : Tree)
}

class graph.GraphFactory {
    ...
}

class newick.TreeFactory {
    ...
}

class LoadGraphService<Graph> extends javafx.concurrent.Service {
    # nodeFile : File
    # edgeFile : File
}
class LoadNewickService<Tree> extends javafx.concurrent.Service {
    # nwkFile : File
}

class Finder<Path> extends java.nio.file.SimpleFileVisitor {
    - matcher : PathMatcher
    - matches : List<Path>

    find()
}
class Workspace {
    - directory : File
    - graphList : List<LoadGraphService>
    - nwkList : List<LoadNewickService>

    -load()
    +getGraphList() : List<LoadGraphService>
    +getNewickList() : List<LoadNewickService>
}

'FXML
class base << (F,orange) FXML >> {
    + base : Text
}
class graph << (F,orange) FXML >> {
    + progressIndicator : ProgressIndicator
    + sequences : Group
}
class load_graph << (F,orange) FXML >> {
    + loadNodes : Button
    + loadEdges : Button
    + load : Button
    + nodeSource : TextField
    + edgeSource : TextField
}
class load_newick << (F,orange) FXML >> {
    + loadNewick : Button
    + load : Button
    + nwkSource : TextField
}
class main << (F,orange) FXML >> {
    + control : VBox
}
class newick << (F,orange) FXML >> {
    + newick : Group
}

'Relations
BaseController "1" *-- "1" base
GraphController "1" *-- "1" graph
LoadGraphController "1" *-- "1" load_graph
LoadNewickController "1" *-- "1" load_newick
MainController "1" *-- "1" main
NewickController "1" *-- "1" newick

App "1" *-- "1" MainController
MainController o-- LoadGraphController
MainController o-- LoadNewickController
MainController o-- MenuController

LoadNewickController o-- NewickController
LoadGraphController o-- GraphController

NewickController -- LoadNewickService
NewickController -- DrawableEdge

GraphController ..> BaseController
GraphController -- DrawableEdge
GraphController -- LoadGraphService

LoadGraphService ..> graph.GraphFactory
LoadNewickService ..> newick.TreeFactory

MainController ..> Workspace
Workspace ..> Finder

'External classes
abstract class javafx.concurrent.Service<V> {
    +createTask() : Task<V>
}

abstract class javafx.application.Application {
    +start(stage : Stage)
}

class org.jgrapht.graph.DefaultDirectedGraph<E, V>

interface javafx.fxml.Initializable {
    +initialize(location : URL, resources : ResourceBundle)
}
@enduml
